Add support for hexnicks 3
dadus33/ChatItem pull request #76
Opened 2023-05-30 02:46 UTC by MagnetiteMC

2023-05-30 09:51 UTC, Elikill58 requested changes
The behavior seems to be the same when it's with v2 or v3, I think it will not works. Can you make this changes? :)

2023-05-30 09:51 UTC, Elikill58 commented on src/main/java/me/dadus33/chatitem/playernamer/hook/HexNicksV3PlayerNamer.java
> +        return BungeeComponentSerializer.get().serialize(HexNicks.api().getStoredNick(p).join());
Seems to be the exact same line than the v2 with same imports.

2023-05-30 09:51 UTC, Elikill58 commented on src/main/java/me/dadus33/chatitem/playernamer/hook/HexNicksV2PlayerNamer.java
> +
useless change xd

2023-05-31 11:43 UTC, MagnetiteMC commented on src/main/java/me/dadus33/chatitem/playernamer/hook/HexNicksV3PlayerNamer.java
> +        return BungeeComponentSerializer.get().serialize(HexNicks.api().getStoredNick(p).join());
Difference is HexNicks.api() vs Nicks.api()

2023-05-31 11:46 UTC, Elikill58 approved these changes

2023-05-31 11:48 UTC, merged